---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emqx
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: emqx-secret
    template:
      engineVersion: v2
      data:
        EMQX_DASHBOARD__DEFAULT_USERNAME: "{{ .EMQX_DASHBOARD_DEFAULT_USERNAME }}"
        EMQX_DASHBOARD__DEFAULT_PASSWORD: "{{ .EMQX_DASHBOARD_DEFAULT_PASSWORD }}"
  dataFrom:
    - extract:
        key: emqx
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emqx-config
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: emqx-config-secret
    template:
      engineVersion: v2
      data:
        init-user.json: |
          [
            {"user_id": "{{ .EMQX_MQTT_WEEWX_USERNAME }}", "password": "{{ .EMQX_MQTT_WEEWX_PASSWORD }}", "is_superuser": false},
            {"user_id": "{{ .EMQX_MQTT_RTL433_USERNAME }}", "password": "{{ .EMQX_MQTT_RTL433_PASSWORD }}", "is_superuser": false},
            {"user_id": "{{ .EMQX_MQTT_ZIGBEE2MQTT_USERNAME }}", "password": "{{ .EMQX_MQTT_ZIGBEE2MQTT_PASSWORD }}", "is_superuser": false},
            {"user_id": "{{ .EMQX_MQTT_RING2MQTT_USERNAME }}", "password": "{{ .EMQX_MQTT_RING2MQTT_PASSWORD }}", "is_superuser": false},
            {"user_id": "{{ .EMQX_MQTT_HOMEASSISTANT_USERNAME }}", "password": "{{ .EMQX_MQTT_HOMEASSISTANT_PASSWORD }}", "is_superuser": false},
            {"user_id": "{{ .EMQX_MQTT_GATUS_USERNAME }}", "password": "{{ .EMQX_MQTT_GATUS_PASSWORD }}", "is_superuser": false}
          ]
        acl.conf: |
          {allow, {user, "{{ .EMQX_MQTT_WEEWX_USERNAME }}"}, all, ["weather/#"]}.
          {allow, {user, "{{ .EMQX_MQTT_WEEWX_USERNAME }}"}, subscribe, ["rtl_433/#"]}.

          {allow, {user, "{{ .EMQX_MQTT_RTL433_USERNAME }}"}, all, ["rtl_433/#"]}.

          {allow, {user, "{{ .EMQX_MQTT_ZIGBEE2MQTT_USERNAME }}"}, all, ["homeassistant/#", "zigbee2mqtt/#"]}.

          {allow, {user, "{{ .EMQX_MQTT_RING2MQTT_USERNAME }}"}, all, ["homeassistant/#", "ring2mqtt/#"]}.

          {allow, {user, "{{ .EMQX_MQTT_HOMEASSISTANT_USERNAME }}"}, all, ["homeassistant/#", "ring2mqtt/#", "zigbee2mqtt/#"]}.
          {allow, {user, "{{ .EMQX_MQTT_HOMEASSISTANT_USERNAME }}"}, subscribe, ["weather/#"]}.

          {allow, {user, "{{ .EMQX_MQTT_GATUS_USERNAME }}"}, all, ["gatus/#"]}.

          {allow, all, subscribe, ["$SYS/#", "weather/#"]}.

          %% Default Deny All
          {deny, all}.
        EMQX_APIKEY_KEY: "{{ .EMQX_APIKEY_KEY }}"
        EMQX_APIKEY_SECRET: "{{ .EMQX_APIKEY_SECRET }}"
  dataFrom:
    - extract:
        key: emqx
